jobs:
  - name: "build-develop"
    plan:
      - get: "repo-develop"
        trigger: true
      - put: "resource-image-develop"
        params:
          build: "repo-develop"
        get_params:
          skip_download: true
  - name: "test-out"
    serial: true
    plan:
      - aggregate:
          - get: "repo-develop"
            trigger: true
            passed:
              - "build-develop"
          - get: "resource-image-develop"
            passed:
              - "build-develop"
            params:
              skip_download: true
      - put: "bosh-lite"
  - name: "test-check-in"
    serial: true
    plan:
      - aggregate:
          - get: "repo"
            resource: "repo-develop"
            passed:
              - "test-out"
          - get: "resource-image-develop"
            passed:
              - "test-out"
            params:
              skip_download: true
          - get: "bosh-lite"
            trigger: true
            passed:
              - "test-out"
      - task: "test"
        file: "repo/ci/tasks/director-info/config.yml"
  - name: "test-delete"
    serial: true
    plan:
      - aggregate:
          - get: "repo-develop"
            passed:
              - "test-check-in"
          - get: "resource-image-develop"
            passed:
              - "test-check-in"
            params:
              skip_download: true
          - get: "bosh-lite"
            trigger: true
            passed:
              - "test-check-in"
      - put: "bosh-lite"
        params:
          delete: true
        get_params:
          allow_deleted: true
  - name: "promote-master"
    serial: true
    plan:
      - aggregate:
          - get: "repo-develop"
            trigger: true
            passed:
              - "test-delete"
          - get: "resource-image-develop"
            passed:
              - "test-delete"
            params:
              rootfs: true
      - aggregate:
        - put: "repo"
          params:
            repository: "repo-develop"
        - put: "resource-image"
          params:
            import_file: "resource-image-develop/rootfs.tar"
          get_params:
            skip_download: true

resources:
  - name: "repo-develop"
    type: "git"
    source:
      uri: {{repo_uri}}
      branch: {{repo_branch_develop}}
      private_key: {{repo_key}}
  - name: "resource-image-develop"
    type: "docker-image"
    source:
      repository: {{images_repo}}
      tag: {{repo_branch_develop}}
      email: {{images_email}}
      username: {{images_username}}
      password: {{images_password}}
      insecure_registries: [{{images_insecure_registries}}]

  - name: "repo"
    type: "git"
    source:
      uri: {{repo_uri}}
      branch: {{repo_branch}}
      private_key: {{repo_key}}
  - name: "resource-image"
    type: "docker-image"
    source:
      repository: {{images_repo}}
      tag: {{repo_branch}}
      email: {{images_email}}
      username: {{images_username}}
      password: {{images_password}}
      insecure_registries: [{{images_insecure_registries}}]

  - name: "bosh-lite"
    type: "aws-bosh-lite"
    source:
      access_key: {{boshlite_access_key}}
      availability_zone: {{boshlite_availability_zone}}
      key_name: {{boshlite_key_name}}
      name: {{boshlite_name}}
      private_ip: {{boshlite_private_ip}}
      secret_key: {{boshlite_secret_key}}
      security_group_id: {{boshlite_security_group_id}}
      subnet_id: {{boshlite_subnet_id}}

resource_types:
  - name: "aws-bosh-lite"
    type: "docker-image"
    source:
      repository: {{images_repo}}
      tag: {{repo_branch_develop}}
      insecure_registries: [{{images_insecure_registries}}]
